name: Deploy to @uniwise/webviewer-ui npm package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: default
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: '@uniwise'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          pnpm cp-webviewer-core
          pnpm jest

      - name: Build
        run: pnpm build

      - name: Version
        run: pnpm version "${GITHUB_REF:11}" --no-git-tag-version

      - name: Publish
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
