name: Deploy to gh pages

on:
  push:
    branches: ['10.0-wf']
    # branches: ['release/*']

jobs:
  branchname:
    runs-on: self-hosted
    outputs:
      branchname: ${{ steps.branchname.outputs.branch }}
    steps:
      - name: Get branch name for destination folder
        shell: bash
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_ENV
        id: branchname
  deploy:
    runs-on: self-hosted
    needs: [branchname]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_READ_TOKEN }}
      - name: Build
        run: yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set remote git repository
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
        env:
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
      - name: Deploy
        run: yarn gh-pages --dist ${dest-directory} --dest ${dest-directory}
    env:
      github_token: ${{ secrets.ACTION_DEPLOY_ACCESS_TOKEN }}
      source-directory: 'build'
      dest-directory: '${{ needs.branchname.outputs.branchname }}/ui'
