name: Deploy to @uniwise/webviewer-ui npm package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: default
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          always-auth: true
          scope: '@uniwise'

      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run cp-webviewer-core
          npm run jest

      - name: Build
        run: npm run build

      - name: Version
        run: npm version "${GITHUB_REF:11}" --no-git-tag-version

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
